import type { Metadata } from "next";
import { Geist, Geist_Mono, Sunflower } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/nav";
import LayoutWrapper from "./components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sunflower = Sunflower({
  weight: ["300", "500", "700"],
  display: "swap",
  style: "normal",
  variable: "--font-sunflower",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="grid min-h-screen">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
